### ISSUE TITLE
Implementacja biblioteki sortującej

### ISSUE THREAD

**Issue by Nikiaker** [Free-Rat/Sorting-Madness-IO#2]
Trzeba znaleźć jakąś bibliotekę z algorytmami sortującymi i zaimplementować ją w naszym programie.
Stworzyć interfesj i klasy według wzorca projektowego [strategia](https://en.wikipedia.org/wiki/Strategy_pattern), w której będzie metoda np. sort(data[], algorithm), gdzie:
data[] - to dane do posortowania
algorithm - jakiś enum, który wyznacza jakim algorytmem te dane posortwoać

Klasa musi też mierzyć czas wykonania danego algorytmu, tak żeby można było je ze sobą porównywać.

Co do wartości zwracanych to dwie opcje:
1. Nie zwraca nic. Po prostu soruje data[]
2. Zwaraca nowy zestaw danych tylko posortowany
3. Do tego trzeba jakoś zwrócić informację o czasie wykonania algortymu

Przykładowy diagram UML:
![Image](https://github.com/Free-Rat/Sorting-Madness-IO/assets/63872921/da5b5e0f-75b5-4da5-a129-3e835b692f8c)

**Comment by Nikiaker** [comment]
Metoda performSort w klasie Sorter. Namęczysz się jak zrobisz funkcję performSort która przyjmuje jako argument string, int albo double, bo będziesz musiał zrobić 3 metody overload, które mają po 3 swtich case'y czyli razem z 9 switch caseów. A jak dodasz nowy algorytm sortowania to musisz dorzucić trzy kolejne case'y.
Moja propozycja - może też naiwna - to zrobić metodę która zwraca "private SortingAlgorithm algorithim" i tyle. Jakaś zewnętrzna klasa jak chce posortować jakieś dane to otrzymuje od sortera algorithm i sobie robi wtedy algorithm.sort()

**Comment by Nikiaker** [comment]
Dla czytelności każda klasa i intefejs w oddzielnym pliku ;)

**Comment by Nikiaker** [comment]
I nie zapomnijmy o komentarzach do metod i klas, bo z tego będzie generowana dokumentacja

**Comment by Free-Rat** [comment]
ok

**Comment by Free-Rat** [comment]
z powodu nie znalezienia odpowiedniej biblioteki, zaimplenetowalem samodzielnie wybrane algorytmy
